import type { Metadata } from "next";
import { Toaster } from "sonner";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>

        {/* 🌈 GLOBAL BACKGROUND */}
        <div className="relative min-h-screen overflow-hidden 
        bg-gradient-to-br from-slate-100 via-white to-blue-100">

          {/* 🔵 Glow 1 (Top Left) */}
          <div className="pointer-events-none absolute top-[-120px] left-[-120px] w-[350px] h-[350px] 
          bg-blue-300 rounded-full blur-3xl opacity-30"></div>

          {/* 🟣 Glow 2 (Bottom Right) */}
          <div className="pointer-events-none absolute bottom-[-120px] right-[-120px] w-[350px] h-[350px] 
          bg-purple-300 rounded-full blur-3xl opacity-30"></div>

          {/* 🟢 Optional Glow 3 (Center soft effect) */}
          <div className="pointer-events-none absolute top-[40%] left-[30%] w-[250px] h-[250px] 
          bg-pink-200 rounded-full blur-3xl opacity-20"></div>

          {/* MAIN CONTENT */}
          <div className="relative z-10">
            <Navbar/>
            <Toaster/>
            {children}
          </div>

        </div>

      </body>
    </html>
  );
}
